---
- name: Init installation Jenkins on Docker Engine
  hosts: jenkins
  become: yes
 
- name: Run a simple command
  community.docker.docker_container_exec:
    container: jenkins-server
    command: sudo cat /var/jenkins_home/secrets/initialAdminPassword
    chdir: /root
  register: result

- name: Print stdout
  debug:
    var: result.stdout

- name: Read initialAdminPassword
  command: dockerexec jenkins-server  sudo cat /var/jenkins_home/secrets/initialAdminPassword


