---
# tasks file for deploy_jenkins
- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/jenkins

- name: Pull the latest official jenkins docker image
  command: docker pull "{{ jenkins_ latest_image }}"

- name: Create a container from the jenkins docker image
  docker_container:
    name: "jenkins-server"
    image: "{{ jenkins_ latest_image }}"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "/share/jenkins:/var/jenkins_home"
    state: present
    recreate: no
    
- name: Copy systemd service script to start and stop the jenkins container
  copy: src=files/jenkins.service dest=/etc/systemd/system

- name: Reload systemctl
  shell: systemctl reload-or-restart jenkins.service

- name: Enable the docker-jenkins service
  shell: systemctl enable jenkins.service
    
- name: Run a simple command
  community.docker.docker_container_exec:
    container: jenkins-server
    command: sudo cat /var/jenkins_home/secrets/initialAdminPassword
    chdir: /root
  register: result

- name: Print stdout
  debug:
    var: result.stdout

